server:
  port: 7075
spring:
  application:
    name: n-t-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VederQC/EXAMEN-main.git # ruta del repositorio git
          searchPaths: config-data
          default-label: conta2
  security:
    user:
      name: root
      password: 123456